export const COMMON_CONST = {
  EMAIL_MAX_LIMIT: 100,
  ONE: 1,
  THREE_SECOND_DELAY: 3000,
  ZERO: 0,
  GRAPHQL_PATH: 'graphql',
  PAGE_SIZE_FIVE: 5,
  PAGE_SIZE_TEN: 10,
  // ===== DIALOG CONFIGURATION =====
  USER_DIALOG_CONFIG: {
    WIDTH: '600px',
    MAX_WIDTH: '95vw',
    DISABLE_CLOSE: true,
    CONFIRM_DIALOG_WIDTH: '400px',
    DELETE_DIALOG_WIDTH: '450px',
  },
};
